/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pucp.pl.readers;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Semaphore;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.DefaultListModel;

/**
 *
 * @author adun
 */
public class AppFrame extends javax.swing.JFrame {

    DefaultListModel readersListModel;
    DefaultListModel writersListModel;
    DefaultListModel resourceListModel;

    List<AppReader> readers;
    List<AppWriter> writers;
    AppResource resource;
    
    Semaphore mx;
    Semaphore wrt;
    AtomicInteger ctr;

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();

        this.readersListModel = new DefaultListModel();
        this.readersList.setModel(readersListModel);
        this.writersListModel = new DefaultListModel();
        this.writersList.setModel(writersListModel);
        this.resourceListModel = new DefaultListModel();
        this.resourceList.setModel(resourceListModel);

        resource = new AppResource(resourceListModel);
        readers = new ArrayList<>();
        writers = new ArrayList<>();

        // Inicialization for simple solution proposed by Curtois
        mx = new Semaphore(1);
        wrt = new Semaphore(1);
        ctr = new AtomicInteger(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        readersList = new javax.swing.JList<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        addReader = new javax.swing.JButton();
        delReader = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        readersSleepTime = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resourceList = new javax.swing.JList<>();
        jPanel19 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        writersList = new javax.swing.JList<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        writersSleepTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Readers - Writers Problem");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Aceptar");
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        mainPanel.setLayout(new java.awt.BorderLayout());
        mainPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);
        mainPanel.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Readers");
        jPanel9.add(jLabel2);

        jPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        readersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(readersList);

        jPanel10.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

        addReader.setText("+");
        addReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReaderMouseClicked(evt);
            }
        });
        addReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReaderActionPerformed(evt);
            }
        });
        jPanel17.add(addReader);

        delReader.setText("-");
        jPanel17.add(delReader);

        jPanel15.add(jPanel17);

        jLabel5.setText("timeout");
        jPanel18.add(jLabel5);

        readersSleepTime.setColumns(4);
        readersSleepTime.setText("500");
        jPanel18.add(readersSleepTime);

        jPanel15.add(jPanel18);

        jPanel6.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Resource");
        jPanel11.add(jLabel3);

        jPanel7.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.BorderLayout());

        resourceList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(resourceList);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel12, java.awt.BorderLayout.CENTER);
        jPanel7.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Writers");
        jPanel13.add(jLabel4);

        jPanel8.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setLayout(new java.awt.BorderLayout());

        writersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(writersList);

        jPanel14.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton3);

        jButton4.setText("-");
        jPanel20.add(jButton4);

        jPanel16.add(jPanel20);

        jLabel6.setText("timeout");
        jPanel21.add(jLabel6);

        writersSleepTime.setColumns(4);
        writersSleepTime.setText("500");
        jPanel21.add(writersSleepTime);

        jPanel16.add(jPanel21);

        jPanel8.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel8);

        mainPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addReaderActionPerformed

    private void addReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReaderMouseClicked
        AppReader reader = new AppReader("reader" + (readers.size() + 1), resource, readersListModel);
        reader.setCtr(ctr);
        reader.setMx(mx);
        reader.setWrt(wrt);
        Integer sleepTime;
        try {
            sleepTime = Integer.valueOf(readersSleepTime.getText());
        }catch(Exception e) {
            sleepTime = 1000;
        }
        reader.setSleepTime(sleepTime);
        reader.start();    
        readers.add(reader);
    }//GEN-LAST:event_addReaderMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        for(AppReader r : readers) {
            r.setStop(true);
        }
        
        for(AppWriter w : writers) {
            w.setStop(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AppWriter writer = new AppWriter("writer" + (writers.size() + 1), resource, writersListModel);
        writer.setCtr(ctr);
        writer.setMx(mx);
        writer.setWrt(wrt);
        Integer sleepTime;
        try {
            sleepTime = Integer.valueOf(writersSleepTime.getText());
        } catch (Exception e) {
            sleepTime = 1000;
        }
        writer.setSleepTime(sleepTime);
        writer.start();
        writers.add(writer);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReader;
    private javax.swing.JButton delReader;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList<String> readersList;
    private javax.swing.JTextField readersSleepTime;
    private javax.swing.JList<String> resourceList;
    private javax.swing.JList<String> writersList;
    private javax.swing.JTextField writersSleepTime;
    // End of variables declaration//GEN-END:variables
}
